global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'hubconductor'
    static_configs:
      - targets: ['hubconductor:3000']
    metrics_path: '/health/metrics'
    scrape_interval: 5s 